### ISSUE TITLE
Update JMS API dependency

### ISSUE THREAD

**Issue by jowerner** [timewalker74/ffmq#2]
Currently, FFMQ depends on **javax.jms.jms-1.1.jar**. For some reason, the JAR for this version is no longer available on Maven, just the POM. Would you mind updating FFMQ's dependencies to **javax.jms.jms-api.1.1-rev-1.jar**? This way, users of FFMQ would not need to explicitly exclude the old, non-existent version and include the new one.

Thanks!

**Comment by timewalker74** [comment]
Fixed on master and available in version 4.0.6 (maven mirrors may take a few hours to update)
