### ISSUE TITLE
Sending a message to a deleted queue breaks the session forever

### ISSUE THREAD

**Issue by andilem** [timewalker74/ffmq#6]
When sending a message to a queue which doesn't exist anymore, an error is logged as expected.

But when sending another message in the same session to another destination, that message is not delivered, and instead the (old) error is logged again. The session is not usable anymore.

Attached is a simple example which shows the problem.
Client 1 connects, sends a message and immediately disconnects.
The server tries to respond, but the queue doesn't exist anymore.
Client 2 then connects, sends a message and waits for a response.
The server sends a response message, which is not delivered, but the old exception is thrown again.

[ffmq-test.zip](https://github.com/timewalker74/ffmq/files/9706872/ffmq-test.zip)

**Comment by timewalker74** [comment]
Thank you for reporting this.
Fix available on master and version 4.0.13 released on maven central (you may have to wait for mirrors update)
